package com.corridometro.ui.theme

import androidx.compose.ui.graphics.Color

// Tema claro em tons de cinza — legível ao sol, visual simples
val Background = Color(0xFFF2F4F7)
val Surface = Color(0xFFFFFFFF)
val SurfaceElevated = Color(0xFFE8ECF1)
val Border = Color(0xFFD0D5DD)
val TextPrimary = Color(0xFF101828)
val TextSecondary = Color(0xFF667085)
val TextMuted = Color(0xFF98A2B3)
val Primary = Color(0xFF16A34A)
val PrimarySoft = Color(0xFFDCFCE7)
val Danger = Color(0xFFDC2626)
val DangerSoft = Color(0xFFFEE2E2)
val Warning = Color(0xFFD97706)

// Marcas das plataformas (aproximação visual para o motorista reconhecer)
val UberBlack = Color(0xFF000000)
val UberForeground = Color(0xFFFFFFFF)
val NinetyNineYellow = Color(0xFFFFDD00)
val NinetyNineForeground = Color(0xFF1A1A1A)
val InDriverTeal = Color(0xFF00A89C)
val InDriverForeground = Color(0xFFFFFFFF)
val OutroGray = Color(0xFF475467)
val OutroForeground = Color(0xFFFFFFFF)
val CabifyPurple = Color(0xFF6B4FBB)
val CabifyForeground = Color(0xFFFFFFFF)
val BoltGreen = Color(0xFF34D186)
val BoltForeground = Color(0xFF1A1A1A)
val LadyDriverPink = Color(0xFFE91E8C)
val LadyDriverForeground = Color(0xFFFFFFFF)
val IFoodRed = Color(0xFFEA1D2C)
val IFoodForeground = Color(0xFFFFFFFF)
val RappiOrange = Color(0xFFFF441F)
val RappiForeground = Color(0xFFFFFFFF)
val LoggiBlue = Color(0xFF0066FF)
val LoggiForeground = Color(0xFFFFFFFF)
val UberEatsGreen = Color(0xFF06C167)
val UberEatsForeground = Color(0xFFFFFFFF)
val MercadoYellow = Color(0xFFFFE600)
val MercadoForeground = Color(0xFF1A1A1A)
val ShopeeOrange = Color(0xFFEE4D2D)
val ShopeeForeground = Color(0xFFFFFFFF)
val AmazonTeal = Color(0xFF232F3E)
val AmazonForeground = Color(0xFFFF9900)
